---
title: "game_sale_6"
author: "Ryu"
date: '2020 4 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(plyr)

library(foreach)

readTsvDates <- function(base.dir, app.name, date.from, date.to) {
  date.from <- as.Date(date.from)
  date.to <- as.Date(date.to)
  dates <- seq.Date(date.from, date.to, by = "day")
  x <- ldply(foreach(day = dates, combine = rbind) %do% {
    read.csv(sprintf("%s/%s/%sdata.tsv", base.dir, app.name, day),
             header = T,
             sep = "\t", stringsAsFactors = F)
  })
  x
}
```

```{r}
readDAU <- function(app.name, date.from, date.to = date.from) {
  data <- readTsvDates("sample-data/section8/daily/dau", app.name,
                       date.from, date.to)
}

readDpu <- function(app.name, date.from, date.to = date.from) {
  data <- readTsvDates("sample-data/section8/daily/dpu", app.name,
                       date.from, date.to)
  data
}

readActionDaily <- function(app.name, date.from, date.to = date.from) {
  data <- readTsvDates("sample-data/section8/daily/action", app.name,
                       date.from, date.to)
  data
}
```


